name: WebRTC C SDK CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  macos-static-builds:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        threadpool: [ON, OFF]
        iot_credentials: [ON, OFF]
        ssl_lib: [openssl, mbedtls]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # macos-13 runner image only supports up to xcode 15.2
          xcode-version: ${{ matrix.arch == 'x86_64' && '15.2' || '15.4' }}

      - name: Check dependencies and set compiler paths
        run: |
          cmake --version
          xcode-select -p
          echo "CC=$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" >> $GITHUB_ENV
          clang --version

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Repository
        run: |
          mkdir build && cd build
          
          cmake .. \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_C_COMPILER=${{ env.CC }} \
            -DCMAKE_CXX_COMPILER=${{ env.CXX }} \
            -DBUILD_STATIC_LIBS=ON \
            -DENABLE_KVS_THREADPOOL=${{ matrix.threadpool }} \
            -DIOT_CORE_ENABLE_CREDENTIALS=${{ matrix.iot_credentials }} \
            -DUSE_OPENSSL=${{ matrix.ssl_lib == 'openssl' && 'ON' || 'OFF' }} \
            -DUSE_MBEDTLS=${{ matrix.ssl_lib == 'mbedtls' && 'ON' || 'OFF' }}
          
          cd ..
          mkdir -p output/build
          mv build output/build
          mv certs output

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-${{ matrix.threadpool }}-${{ matrix.iot_credentials }}-${{ matrix.ssl_lib }}
          path: ./output
