name: WebRTC C SDK CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  macos-static-builds:
    runs-on: macos-14
    strategy:
      matrix:
        architecture: [ x86_64, arm64 ]
    env:
      CC: $(brew --prefix llvm@15)/bin/clang
      CXX: $(brew --prefix llvm@15)/bin/clang++
    steps:
      - name: Check dependencies
        run: |
          cmake --version

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Repository
        run: |
          mkdir build && cd build
          if [[ "${{ matrix.architecture }}" == "x86_64" ]]; then
            cmake .. -DCMAKE_OSX_ARCHITECTURES=x86_64 -DBUILD_STATIC_LIBS=ON -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=darwin-x86_64
          elif [[ "${{ matrix.architecture }}" == "arm64" ]]; then
            cmake .. -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_STATIC_LIBS=ON -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=darwin-arm64
          fi
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.architecture }}-build
          path: ./build
