name: WebRTC C SDK CI
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  linux-cross-compilation:
    strategy:
      matrix:
        os:
          - name: mips-32
            runner: Ubuntu-22.04
            install: gcc-mips-linux-gnu g++-mips-linux-gnu
            cc: mips-linux-gnu-gcc
            cxx: mips-linux-gnu-g++
            additional-cmake: -DBUILD_OPENSSL_PLATFORM=linux-mips32 -DBUILD_LIBSRTP_DESTINATION_PLATFORM=mips-unknown-linux-gnu
            file-contents: ELF 32-bit LSB shared object, MIPS, MIPS32
        config:
          - name: Shared OpenSSL
            cmake_flags: -DBUILD_TEST=ON
          - name: Static OpenSSL
            cmake_flags: -DBUILD_TEST=ON -DBUILD_STATIC_LIBS=TRUE
          - name: Shared MbedTLS
            cmake_flags: -DBUILD_TEST=ON -DUSE_OPENSSL=OFF -DUSE_MBEDTLS=ON
          - name: Static MbedTLS
            cmake_flags: -DBUILD_TEST=ON -DBUILD_STATIC_LIBS=TRUE -DUSE_OPENSSL=OFF
              -DUSE_MBEDTLS=ON
      fail-fast: false
    env:
      AWS_KVS_LOG_LEVEL: 2
    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.os.name }}, ${{ matrix.config.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.os.install }}
      - name: Configure and build ${{ matrix.config.name }}
        run: >
          export CC=${{ matrix.os.cc }}

          export CXX=${{ matrix.os.cxx }}

          echo "Using $CC and $CXX"


          mkdir -p build

          cd build


          cmake .. ${{ matrix.config.cmake_flags }} ${{ matrix.os.additional-cmake }} -DENABLE_AWS_SDK_IN_TESTS=OFF

          make -j$(sysctl -n hw.ncpu)
        shell: bash
      - name: Check test file is compiled correctly
        run: |
          file ./tst/webrtc_client_test | grep "${{ matrix.os.file-contents }}"
        shell: bash
