name: WebRTC C SDK CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  macos-static-builds:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        threadpool: [ON, OFF]
        iot_credentials: [ON, OFF]
        ssl_lib: [openssl, mbedtls]
    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
    steps:
      - name: Check dependencies
        run: cmake --version

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Repository
        run: |
          export CC=$(brew --prefix llvm@15)/bin/clang
          export CXX=$(brew --prefix llvm@15)/bin/clang++

          mkdir build && cd build
          
          cmake .. \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DBUILD_STATIC_LIBS=ON \
            -DENABLE_KVS_THREADPOOL=${{ matrix.threadpool }} \
            -DIOT_CORE_ENABLE_CREDENTIALS=${{ matrix.iot_credentials }} \
            -DUSE_OPENSSL=${{ matrix.ssl_lib == 'openssl' && 'ON' || 'OFF' }} \
            -DUSE_MBEDTLS=${{ matrix.ssl_lib == 'mbedtls' && 'ON' || 'OFF' }}
          
          make
          
          cd ..
          mkdir -p output/build
          mv build output/build
          mv certs output

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-${{ matrix.threadpool }}-${{ matrix.iot_credentials }}-${{ matrix.ssl_lib }}
          path: ./output
