name: Codecov for WebRTC C SDK
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  AWS_KVS_LOG_LEVEL: 7

jobs:
  linux-gcc-codecov:
    if: ${{ github.repo == 'awslabs/amazon-kinesis-video-streams-webrtc-sdk-c' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build repository
        run: |
          mkdir build 
          cd build
          cmake .. -DCODE_COVERAGE=ON -DBUILD_TEST=ON
          make -j

      - name: Run tests
        working-directory: ./build
        run: |
          ./tst/webrtc_client_test

      - name: Code coverage
        run: |
          for test_file in $(find CMakeFiles/kvsWebrtcClient.dir CMakeFiles/kvsWebrtcSignalingClient.dir -name '*.gcno'); do gcov $test_file; done
          bash <(curl -s https://codecov.io/bash)
